services:
  backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend:/app
      - ./database:/app/database

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
