services:
  backend:
    container_name: fastapi_backend
    image: ghcr.io/dejwodejo/monitor_backend:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./database:/app/database

  frontend:
    container_name: nginx_front
    image: ghcr.io/dejwodejo/monitor_frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
