services:
  backend:
    container_name: fastapi_backend
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./database:/app/database # Only keep database volume

  frontend:
    container_name: nginx_front
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
