name: update app via ghcr

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE: ${{github.actor}}/monitor_backend:latest
  FRONTEND_IMAGE: ${{github.actor}}/monitor_frontend:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: login
      run: |
        echo ${{secrets.PAT}} | docker login ghcr.io -u ${{github.actor}} --password-stdin
    - name: build and publish backend
      run: |
        docker build ./backend --tag ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}
        docker push ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}
    - name: build and publish frontend
      run: |
        docker build ./frontend --tag ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}
        docker push ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}

  deploy:
    needs: publish
    name: deploy images
    runs-on: ubuntu-22.04

    steps:
    - name: Test simple SSH
      run: ssh ${{secrets.VPS_USERNAME}}@${{secrets.VPS_HOST}} -p ${{secrets.VPS_PORT}} "echo 'Connection successful'"
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -p ${{secrets.VPS_PORT}} -H ${{secrets.VPS_USERNAME}}@${{secrets.VPS_HOST}} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{secrets.VPS_USERNAME}}@${{secrets.VPS_HOST}} -p ${{secrets.VPS_PORT}} "cd ${{ secrets.VPS_PROJECT_PATH }} && docker compose pull && docker compose up -d && exit"
    - name: cleanup
      run: rm -rf ~/.ssh