name: deploy new stuff

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: deploy images
    runs-on: ubuntu-22.04

    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_HOST_KEY }}" > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
    - name: fetch code and build container
      run: |
        ssh ${{secrets.VPS_USERNAME}}@${{secrets.VPS_HOST}} -p ${{secrets.VPS_PORT}} "cd ${{ secrets.VPS_PROJECT_PATH }} && \
        git pull origin main && \
        docker compose down && \
        docker compose build --no-cache && \
        docker compose up -d && \
        echo '--- CONTAINER STATUS ---' && \
        docker compose ps && \
        echo '--- CONTAINER LOGS ---' && \
        docker compose logs && \
        exit"
    - name: cleanup
      run: rm -rf ~/.ssh